config/routes.rb
Holoteca::Application.routes.draw do
  get '/não-encontramos',  to: "errors#error_404", as: :error_404

  scope '/admin' do
    devise_for :users,
      controllers: {
        registrations: 'admin/registrations',
        sessions: 'admin/sessions',
        passwords: 'admin/passwords'
      }
  end

  namespace :admin do
    root to: 'dashboard#index'
    get '/clean', to: "dashboard#clear_cache"
    resources :archives, only: [ :index, :create ]
    resources :categories, only: [ :index, :create, :edit, :update ]
    resources :subscribers
    resources :articles
  end

  get 'privacidade', to: 'statics#privacy', as: :privacy
  get 'anuncie', to: 'statics#contact', as: :contact
  post 'assine', to: 'statics#subscribe', as: :subscribe

  get '/uploads/archives/:id/:filename', to: 'archives#image'
  get '/tag/:id',    to: 'holo#tag',      as: :tag
  get '/autor/:id',  to: 'holo#author',   as: :author
  get '/holos/:id',  to: 'holo#category', as: :category
  get ':article_id', to: 'holo#article',  as: :article

  root to: 'holo#index'
end

app/controllers/holo_controller.rb
class HoloController < ApplicationController
  include SidebarTron

  def index
    @featured_slide = Article.featured unless fragment_exist? 'featured_posts'
    @articles = Article.includes(:category, :author).visible

    if @featured_slide # prevent repeat posts
      @articles = @articles.where(:id.nin => @featured_slide.pluck(:id))
    end

    fresh_when last_modified: @articles.last.try(:published_at).try(:utc), public: true
  end

  def article
    @resource = Article.by_slug params[:article_id]
    return oh_not_found unless @resource and @resource.published?

    @related = Article.related @resource.tags.pluck(:name), @resource.id
    @featured = @resource.category.articles.lastest.limit(5) if @related.empty?
    fresh_when etag: @resource, last_modified: @resource.published_at.utc, public: true
  end

  def category
    @resource = Category.includes(:articles).by_slug(params[:id])
    return oh_not_found unless @resource

    @featured = Article.featured.limit 5
    fresh_when etag: @resource, last_modified: @resource.updated_at.try(:utc), public: true
  end

  def tag
    @resource = Tag.includes(:articles).by_slug(params[:id])
    return oh_not_found unless @resource
    
    @related = Article.related [@resource.name], ''
    @featured = @resource.articles.lastest.limit(5) if @related.empty?
    fresh_when etag: @resource, public: true
  end

  def author
    @resource = User.includes(:articles).by_slug(params[:id])
    return oh_not_found unless @resource
    
    @featured = Article.featured.limit 5
    fresh_when etag: @resource, public: true
  end

end

app/views/holo/_article.html.erb
<% cache([article, "card"]) do %>
<article class="post col-sm-12 <%= article.category.to_param %>">

  <div class="entry-image">
    <div class="entry-category">
      <% if article.category %><%= link_to article.category.name, category_path(article.category), title: article.category.name %><% end %>
    </div>
    <%= link_to article_path(article), title: article.title do %>
      <%= image_tag cover(article.cover_url), alt: article.title, class: 'img-responsive' %>
      <div class="overlay"><i class="fa fa-plus-circle"></i></div>
    <% end %>
  </div>

  <div class="entry-main">

    <h2 class="entry-title">
      <%= link_to article.title, article_path(article), title: article.title %>
    </h2>

    <div class="entry-meta">
      <span class="entry-date updated">
        <%= link_to article_path(article), title: article.title do %>
          <i class="fa fa-clock-o"></i>
          <time datetime=""><%= date_for article.published_at %></time>
        <% end %>
      </span>

      <span class="vcard">
        <%= link_to author_path(article.author), title: article.author.name, class: 'url fn' do %>
          <i class="fa fa-user"></i>
          <span><%= article.author.name %></span>
        <% end %>
      </span>
    </div>

    <div class="entry-content"><%= raw article.summary %></div>
    <%#= link_to 'Ler Mais', article_path(article), title: article.title, class: 'btn readmore' %>
  </div>
  <div class="clear"></div>

</article>
<% end %>

app/views/holo/_author.html.erb
<div class="author-info">
  <div class="author-avatar">
    <%= image_tag gravatar_url(resource.email), class: 'avatar photo', alt: resource.name, size: '100x100' %>
  </div>

  <div class="author-description author-link">
    <h2><%= resource.name %></h2>

    <%= link_to author_path(resource), rel: 'author', title: resource.name do %>
      Todos os posts de <%= resource.name %>      <span class="meta-nav">→</span>
    <% end %>

    <p><%= resource.about %></p>
  </div>

  <div class="widget_g7_social">
    <ul class="horizontal circle">

      <% unless resource.facebook.blank? %>
      <li class="social-facebook">
        <%= link_to url_for(resource.facebook), target: '_blank', title: 'Facebook' do %>
          <span class="social-box">
            <i class="fa fa-facebook"></i>
          </span>
        <% end %>
      </li>
      <% end %>

      <% unless resource.gplus.blank? %>
      <li class="social-google">
        <%= link_to "#{url_for(resource.gplus)}?rel=author", target: '_blank', title: 'Google Plus' do %>
          <span class="social-box">
            <i class="fa fa-google-plus"></i>
          </span>
        <% end %>
      </li>
      <% end %>

      <% unless resource.twitter.blank? %>
      <li class="social-twitter">
        <%= link_to url_for(resource.twitter), target: '_blank', title: 'Twitter' do %>
          <span class="social-box">
            <i class="fa fa-twitter"></i>
          </span>
        <% end %>
      </li>
      <% end %>

      <% unless resource.site.blank? %>
        <li class="author-website">
          <i class="fa fa-external-link"></i>
          <%= link_to resource.site, url_for(resource.site), target: '_blank' %>
        </li>
      <% end %>

    </ul>
    <div class="clear"></div>
  </div>
</div>

app/views/holo/article.html.erb
<%
  seo [
    { property: 'description', content: "#{@resource.title}. #{@resource.summary}" },
    { property: 'og:title', content: @resource.title, type: 'property' },
    { property: 'og:image', content: @resource.cover_url, type: 'property' },
    { property: 'og:description', content: @resource.summary, type: 'property' },
    { property: 'twitter:creator', content: @resource.title },
    { property: 'twitter:title', content: @resource.title },
    { property: 'twitter:description', content: @resource.summary },
    { property: 'twitter:image:src', content: @resource.cover_url }
  ]
  title "#{@resource.title} / Holoteca"
%>

<article class="post single">

  <header class="entry-header">
    <% unless @resource.cover_url.nil? || @resource.cover_url.blank? %>
      <div class="entry-image">
        <%= image_tag @resource.cover_url, alt: @resource.title, class: "img-responsive" %>
      </div>
    <% end %>

    <h1 class="entry-title"><%= @resource.title %></h1>

    <div class="entry-meta">
      <% if @resource.category %>
      <span class="entry-category">
        <%= link_to category_path(@resource.category), title: @resource.category.name do %>
          <%= @resource.category.name %>
        <% end %>
      </span>
      <% end %>

      <span class="entry-date updated">
        <%= link_to article_path(@resource), title: @resource.title do %>
          <i class="fa fa-clock-o"></i>
          <time datetime=""><%= date_for @resource.published_at %></time>
        <% end %>
      </span>

      <span class="vcard">
        <%= link_to author_path(@resource.author), class: 'url fn', title: @resource.author.name do %>
          <i class="fa fa-user"></i>
          <span><%= @resource.author.name %></span>
        <% end %>
      </span>
    </div>
  </header>

  <div class="entry-content">
    <%= raw @resource.body %>
  </div>

  <footer class="entry-footer">
    <div>
      <% unless @resource.font.nil? or @resource.font.blank? %><p>Fonte: <%= link_to @resource.font, @resource.font %></p><br /><% end %>
      <% @resource.tags.each do |tag| %>
        <span class="block-title">
        <%= link_to tag_path(tag), rel: 'tag' do %>
          <%= tag.name %>    <i class="fa fa-angle-right"></i>
        <% end %>
        </span>
      <% end %>
    </div>

    <nav class="next-prev clearfix">
      <div class='shareaholic-canvas' data-app='share_buttons' data-app-id='5630529'></div>
    </nav>

  </footer>

</article>

<%= render partial: 'author', locals: { resource: @resource.author } %>

<div class="fb-comments" data-href="<%= url(request.path) %>" data-width="720" data-numposts="5" data-colorscheme="light"></div>

<ins class="adsbygoogle"
  style="display:inline-block;width:728px;height:90px;"
  data-ad-client="ca-pub-9856374304140488"
  data-ad-slot="3952615489"></ins>
<script>(adsbygoogle = window.adsbygoogle || []).push({});</script>

app/views/holo/author.html.erb
<%
  seo [
    { property: 'description', content: "#{@resource.name}. #{@resource.try(:about)}" },
    { property: 'og:title', content: @resource.about, type: 'property' },
    { property: 'og:image', content: gravatar_url(@resource.email), type: 'property' },
    { property: 'og:description', content: @resource.about, type: 'property' },
    { property: 'twitter:title', content: @resource.name },
    { property: 'twitter:description', content: @resource.about },
    { property: 'twitter:image:src', content: gravatar_url(@resource.email) }
  ]
  title "#{@resource.name} / Holoteca"
%>

<header class="archive-header">
  <%= render partial: 'author', locals: { resource: @resource } %>
</header>

<div class='posts blog-small'>
  <% @resource.articles.visible.each do |article| %>
    <%= render partial: 'article', locals: { article: article } %>
  <% end %>
</div>

app/views/holo/category.html.erb
<%
  seo [
    { property: 'description', content: "#{@resource.name}. #{@resource.summary}" },
    { property: 'og:title', content: @resource.name, type: 'property' },
    { property: 'og:image', content: image_url('logos/symbol-holoteca.png'), type: 'property' },
    { property: 'og:description', content: @resource.summary, type: 'property' },
    { property: 'twitter:title', content: @resource.name },
    { property: 'twitter:description', content: @resource.summary },
    { property: 'twitter:image:src', content: image_url('logos/symbol-holoteca.png') }
  ]
  title "#{@resource.name} / Holoteca"
%>

<header class="archive-header">
  <br>
  <h1 class="page-title"><%= @resource.name %></h1>
  <p><%= @resource.summary %></p>
</header>

<div class='posts blog-large'>
  <div class="row">
    <% @resource.articles.visible.each do |article| %>
      <%= render partial: 'article', locals: { article: article } %>
    <% end %>
  </div>
</div>

<ins class="adsbygoogle"
     style="display:inline-block;width:728px;height:90px"
     data-ad-client="ca-pub-9856374304140488"
     data-ad-slot="8289816284"></ins>
<script>(adsbygoogle = window.adsbygoogle || []).push({});</script>

app/views/holo/index.html.erb
<%
  seo [
    { property: 'description', content: 'Textos que ficam!' },
    { property: 'og:title', content: 'Holoteca', type: 'property' },
    { property: 'og:image', content: image_url('logos/symbol-holoteca.png'), type: 'property' },
    { property: 'og:description', content: 'Textos que ficam!', type: 'property' },
    { property: 'twitter:title', content: 'Holoteca' },
    { property: 'twitter:description', content: 'Textos que ficam!' },
    { property: 'twitter:image:src', content: image_url('logos/symbol-holoteca.png') }
  ]
  title 'Holoteca'
%>

<div class="posts blog-masonry">
  <div class="row">

  <% cache('featured_posts', skip_digest: true) do %>
    <div class="flexslider featured">
      <ul class="slides">
        <% @featured_slide.each do |article| %>
          <li class="post <%= article.category.try(:permalink) %>">
            <%= link_to article_path(article), title: article.title do %>
              <%= image_tag cover(article.cover_url), class: 'img-responsive', alt: article.title %>
            <% end %>
            <header>
              <span class="entry-category">
                <% if article.category %><%= link_to article.category.name, category_path(article.category) %><% end %>
              </span>
              <h2><%= link_to article.title, article_path(article), title: article.title%></h2>
            </header>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% @articles.each do |article| %>
    <% cache([article, "card"]) do %>
    <article class="post col-sm-6 col-md-6 <%= article.category.try(:permalink) %>">
      <div class="entry-image">
        <div class="entry-category">
          <% if article.category %><%= link_to article.category.name, category_path(article.category) %><% end %>
        </div>
        <%= link_to article_path(article), title: article.title do %>
          <%= image_tag cover(article.cover_url), size: '320x190', alt: article.title, class: 'img-responsive' %>
          <div class="overlay"><i class="fa fa-plus-circle"></i></div>
        <% end %>
      </div>

      <div class="entry-main">
        <h2 class="entry-title">
          <%= link_to article.title, article_path(article) %>
        </h2>
        <div class="entry-meta">
          <span class="entry-date updated">
            <%= link_to article_path(article), title: article.title do %>
              <i class="fa fa-clock-o"></i>
              <time datetime="<%= moment_for(article.published_at) %>"><%= date_for article.published_at %></time>
            <% end %>
          </span>
          <span class="vcard">
            <%= link_to author_path(article.author), class: 'url fn', title: article.author.name do %>
              <i class="fa fa-user"></i>
              <span><%= article.author.name %></span>
            <% end %>
          </span>
        </div>
        <div class="entry-content"><%= raw article.summary %></div>
      </div>
    </article>
    <% end %>
  <% end %>

  <article class="col-sm-6 col-md-6 no-gutter">
    <ins class="adsbygoogle"
      style="display:inline-block;width:336px;height:280px"
      data-ad-client="ca-pub-9856374304140488"
      data-ad-slot="9080819088"></ins>
    <script>(adsbygoogle = window.adsbygoogle || []).push({});</script>
  </article>

  </div>
</div>

app/views/holo/tag.html.erb
<%
  seo [
    { property: 'description', content: "O Holoteca é uma revista sobre diversos assuntos. Encontre tudo sobre #{@resource.name} aqui." },
    { property: 'og:title', content: @resource.name, type: 'property' },
    { property: 'og:image', content: image_url('logos/symbol-holoteca.png'), type: 'property' },
    { property: 'og:description', content: "O Holoteca é uma revista sobre diversos assuntos. Encontre tudo sobre #{@resource.name} aqui.", type: 'property' },
    { property: 'twitter:title', content: @resource.name },
    { property: 'twitter:description', content: "O Holoteca é uma revista sobre diversos assuntos. Encontre tudo sobre #{@resource.name} aqui." },
    { property: 'twitter:image:src', content: image_url('logos/symbol-holoteca.png') }
  ]
  title "#{@resource.name} / Holoteca"
%>

<ins class="adsbygoogle"
     style="display:inline-block;width:728px;height:90px"
     data-ad-client="ca-pub-9856374304140488"
     data-ad-slot="6813083082"></ins>
<script>(adsbygoogle = window.adsbygoogle || []).push({});</script><br>

<header class="archive-header">
  <h1 class="page-title"><%= @resource.name %></h1>
</header>

<div class='posts blog-small'>
  <% @resource.articles.visible.each do |article| %>
    <%= render partial: 'article', locals: { article: article } %>
  <% end %>
</div>

<ins class="adsbygoogle"
     style="display:inline-block;width:728px;height:90px"
     data-ad-client="ca-pub-9856374304140488"
     data-ad-slot="8289816284"></ins>
<script>(adsbygoogle = window.adsbygoogle || []).push({});</script>