config/routes.rb
Holoteca::Application.routes.draw do
  get '/não-encontramos',  to: "errors#error_404", as: :error_404

  scope '/admin' do
    devise_for :users,
      controllers: {
        registrations: 'admin/registrations',
        sessions: 'admin/sessions',
        passwords: 'admin/passwords'
      }
  end

  namespace :admin do
    root to: 'dashboard#index'
    get '/clean', to: "dashboard#clear_cache"
    resources :archives, only: [ :index, :create ]
    resources :categories, only: [ :index, :create, :edit, :update ]
    resources :subscribers
    resources :articles
  end

  get 'privacidade', to: 'statics#privacy', as: :privacy
  get 'anuncie', to: 'statics#contact', as: :contact
  post 'assine', to: 'statics#subscribe', as: :subscribe

  get '/uploads/archives/:id/:filename', to: 'archives#image'
  get '/tag/:id',    to: 'holo#tag',      as: :tag
  get '/autor/:id',  to: 'holo#author',   as: :author
  get '/holos/:id',  to: 'holo#category', as: :category
  get ':article_id', to: 'holo#article',  as: :article

  root to: 'holo#index'
end

app/models/article.rb
class Article
  include Mongoid::Document
  include Mongoid::Timestamps::Updated
  include Taggable
  include Sluggable

  field :title,       type: String
  field :body,        type: String
  field :published,   type: Mongoid::Boolean, default: false
  field :featured,    type: Mongoid::Boolean, default: true
  field :published_at, type: Time, default: ->{ Time.now }
  field :summary,     type: String
  field :permalink,   type: String
  field :cover_url,   type: String
  field :font,        type: String
  field :keywords,    type: Array
  field :meta,        type: Hash, default: { sent: false }

  # metas:
  #   sent: flag to sent article on newsletter 

  index({ title: 1, permalink: 1 }, { unique: true, drop_dups: true })
  
  validates :title, :body, :summary, :category, :author, presence: true
  validates :title, :permalink, uniqueness: { case_sensitive: false, messsage: 'Tente outro título' }

  belongs_to :author, class_name: 'User', index: true, touch: true
  belongs_to :category, index: true, touch: true

  alias_attribute :name, :title

  scope :visible, ->{ where(published: true).order(published_at: :desc).cache }
  scope :lastest, ->{ visible.limit(8) }
  scope :featured, ->{ visible.where(featured: true).limit(8) }
  scope :unread, ->{ visible.where(meta: { sent: false }) }
  scope :related, ->(keys, id){ visible.nin(_id: id).in(keywords: keys).limit(3).cache }

  before_save :publish
  after_save :to_keys

  def publish
    self.published_at = Time.now if self.published_changed?
  end

  def to_keys
    self.keywords = []
    self.tags.pluck(:name).each { |key| self.keywords.push key }
  end

end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < InheritedResources::Base
  include Cacheable

  before_filter :authenticate_user!
  after_filter :expire_modules,   only: [ :create, :update, :destroy ]
  after_filter :expire_resource,  only: [ :update ]

  defaults finder: :by_slug
  layout 'admin'

  def index
    @articles = current_user.admin? ? collection.order(published_at: :desc) : current_user.articles.order(published_at: :desc)
    super
  end

  def create
    resource = Article.new permitted_params[:article]
    resource.taggify params[:article][:tags]
    create!
  end

  def update
    resource.taggify params[:article][:tags]
    update!
  end

  def destroy
    resource.update(published: false)
    redirect_to :back, notice: 'Não é possível remover! Artigo despublicado.'
  end

  protected

    def permitted_params
      params.permit article: [ :category, :author, :title, :summary, :body, :published, :featured, :font, :cover_url, tags: [] ]
    end

end

app/views/admin/articles/_form.html.erb
<div class="box box-danger">
  <%= form_for([:admin, resource], html: { role: :form }) do |f| %>
    <div class="box-header">
      <h3 class="box-title">Novo Artigo <%= label_for resource.published unless resource.new_record? %></h3>
      <div class="box-tools">
        <div class="btn-group pull-right">
          <%= link_to raw('<i class="fa fa-caret-left"></i> Todos'), admin_articles_path, class: 'btn btn-sm btn-default' %>

          <% unless resource.new_record? %>
          <%= link_to raw('<i class="fa fa-external-link"></i>'), article_path(resource), class: 'btn btn-sm btn-default' %>
          <%= link_to raw('<i class="fa fa-times"></i>'), admin_article_path(resource), class: 'btn btn-sm btn-default', method: :delete, data: { confirm: 'Tem certeza?' } %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="box-body pad">
      <div class='row'>
        <div class="form-group col-md-6">
          <%= f.label :category, 'Categoria' %>
          <%= f.select :category, Category.all.collect{ |category| [category.name, category.id] }, { selected: resource.category.try(:id) }, { class: 'form-control', required: true } %>
        </div>
        <div class="form-group col-md-6">
          <%= f.label :author, 'Autor' %>
          <%= f.select :author, User.all.collect{ |author| [author.name, author.id] }, { selected: (resource.new_record? ? current_user.id : resource.author.id) }, { class: 'form-control', required: true } %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :cover_url, 'URL da imagem da capa' %>
        <%= f.text_field :cover_url, placeholder: 'link externo', class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :title, 'Título' %>
        <%= f.text_field :title, placeholder: 'Título', class: 'form-control', required: true %>
      </div>
      <div class="form-group">
        <%= f.label :summary, 'Resumo' %> <i> (Chamada)</i>
        <%= f.text_field :summary, placeholder: 'Resumo', class: 'form-control', required: true %>
      </div>

      <div class="form-group">
        <%= f.label :body, 'Texto' %>
        <%= f.text_area :body, class: 'form-control', placeholder: 'Lorem Ipsum', style: "width: 100%; height: 600px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;" %>
      </div>

      <% if resource.permalink %>
      <div class="form-group">
        <%= f.label :permalink %> <i>
        <%= f.text_field :permalink, class: 'form-control', disabled: true %>
      </div>
      <% end %>

      <div class="form-group">
        <%= f.label :tags, 'Tags' %>
        <%= f.text_field :tags, placeholder: 'Adicionar Tag', class: 'form-control', data: { role: 'tagsinput' }, value: (resource.tags.empty? ? '' : resource.taggable) %>
      </div>

      <div class="form-group">
        <%= f.label :font, 'Fonte' %> <i>
        <%= f.text_field :font, class: 'form-control' %>
      </div>

      <div class="form-group">
        <label>
          <%= f.check_box :published, class: 'icheckbox_square-red' %>
          Publicar?
        </label>
      </div>

      <div class="form-group">
        <label>
          <%= f.check_box :featured, class: 'icheckbox_square-red' %>
          Destaque?
        </label>
      </div>
    </div>
    <div class="box-footer">
      <%= f.submit "Salvar", class: 'btn btn-default' %>
    </div>
  <% end %>
</div>

app/views/admin/articles/edit.html.erb
<section class="content-header">
  <h1>Artigos <small>Editar Artigo</small></h1>
</section>

<section class="content">

  <div class="row">
    <div class="col-md-12">
      <%= render 'form' %>
    </div>
  </div>

</section>

app/views/admin/articles/index.html.erb
<section class="content-header">
  <h1>Artigos <small>Todos</small></h1>
</section>

<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <div class="box box-danger">
        <div class="box-header">
            <h3 class="box-title">Artigos</h3>
            <div class="box-tools">
              <%= link_to 'Novo Artigo', new_admin_article_path, class: 'btn btn-sm btn-default pull-right' %>
              <!--
              TODO: search
                <div class="input-group">
                  <input type="text" name="table_search" class="form-control input-sm pull-right" style="width: 150px;" placeholder="Search"/>
                  <div class="input-group-btn">
                    <button class="btn btn-sm btn-default"><i class="fa fa-search"></i></button>
                  </div>
                </div>
              -->
            </div>
        </div>

        <div class="box-body table-responsive">
          <table class="table table-hover">
            <tr>
              <th>Título</th>
              <th>Autor</th>
              <th>Categoria</th>
              <th>Data</th>
              <th>Status</th>
              <th></th>
            </tr>
            <% @articles.each do |article| %>
              <tr>
                <td><%= link_to article.title, admin_article_path(article) %></td>
                <td><%= article.author.name %></td>
                <td><%= article.category.try :name %></td>
                <td><%= date_for article.published_at %></td>
                <td>
                  <%= label_for article.published %>
                  <% if article.featured %><span class='label label-danger'>Destaque</span><% end %>
                </td>
                <td>
                  <div class="btn-group">
                    <%= link_to raw('<i class="fa fa-external-link"></i>'), article_path(article), class: 'btn btn-sm btn-default', title: 'Ver no Site' %>
                    <%= link_to raw('<i class="fa fa-edit"> </i>'), edit_admin_article_path(article), class: 'btn btn-sm btn-default' %>
                    <%= link_to raw('<i class="fa fa-times"></i>'), admin_article_path(article), class: 'btn btn-sm btn-default', method: :delete, data: { confirm: 'Tem certeza?' } %>
                  </div>
                </td>
              </tr>
            <% end %>
          </table>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/admin/articles/new.html.erb
<section class="content-header">
  <h1>Artigos <small>Novo Artigo</small></h1>
</section>

<section class="content">

  <div class="row">
    <div class="col-md-12">
      <%= render 'form' %>
    </div>
  </div>

</section>

app/views/admin/articles/show.html.erb
<section class="content-header">
  <h1>Artigos <small>Post</small></h1>
</section>

<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <div class="box box-danger">
        <div class="box-header">
            <h3 class="box-title"></h3>
            <div class="box-tools">
              <%= label_for resource.published %> <% if resource.featured %><span class='label label-danger'>Destaque</span><% end %>
              <div class="btn-group pull-right">
                <%= link_to raw('<i class="fa fa-caret-left"></i> Todos'), admin_articles_path, class: 'btn btn-sm btn-default' %>
                <%= link_to raw('<i class="fa fa-external-link"></i>'), article_path(resource), class: 'btn btn-sm btn-default' %>
                <%= link_to raw('<i class="fa fa-plus"></i>'), new_admin_article_path, class: 'btn btn-sm btn-default' %>
                <%= link_to raw('<i class="fa fa-edit"></i>'), edit_admin_article_path(resource), class: 'btn btn-sm btn-default' %>
                <%= link_to raw('<i class="fa fa-times"></i>'), admin_article_path(resource), class: 'btn btn-sm btn-default', method: :delete, dat: { confirm: 'Tem certeza?' } %>
              </div>
              <!--
              TODO: search
                <div class="input-group">
                  <input type="text" name="table_search" class="form-control input-sm pull-right" style="width: 150px;" placeholder="Search"/>
                  <div class="input-group-btn">
                    <button class="btn btn-sm btn-default"><i class="fa fa-search"></i></button>
                  </div>
                </div>
              -->
            </div>
        </div>

        <div class="box-body">
          <h5 class='pull-right'>
            <i class="fa fa-folder-o"></i> <%= resource.category.try :name %>
            <i class="fa fa-user"></i> <%= resource.author.try :name %>
            <i class="fa fa-calendar"></i> <%= date_for resource.published_at %>
          </h5>
          <%= image_tag resource.cover_url, class: 'cover' %>
          <h1><%= resource.title %></h1>
          <h3><blockquote><%= raw resource.summary %></blockquote><br /></h3>

          <%= raw resource.body %>

          <br />
          <h4><% resource.tags.each do |tag| %> <span class="label label-primary"><%= tag.name %></span> <% end %></h4>
          <br />
          <% unless resource.font.nil? or resource.font.blank? %><p>Fonte: <%= link_to resource.font, resource.font %></p><% end %>

        </div>
      </div>
    </div>
  </div>
</section>