config/routes.rb
Holoteca::Application.routes.draw do
  get '/não-encontramos',  to: "errors#error_404", as: :error_404

  scope '/admin' do
    devise_for :users,
      controllers: {
        registrations: 'admin/registrations',
        sessions: 'admin/sessions',
        passwords: 'admin/passwords'
      }
  end

  namespace :admin do
    root to: 'dashboard#index'
    get '/clean', to: "dashboard#clear_cache"
    resources :archives, only: [ :index, :create ]
    resources :categories, only: [ :index, :create, :edit, :update ]
    resources :subscribers
    resources :articles
  end

  get 'privacidade', to: 'statics#privacy', as: :privacy
  get 'anuncie', to: 'statics#contact', as: :contact
  post 'assine', to: 'statics#subscribe', as: :subscribe

  get '/uploads/archives/:id/:filename', to: 'archives#image'
  get '/tag/:id',    to: 'holo#tag',      as: :tag
  get '/autor/:id',  to: 'holo#author',   as: :author
  get '/holos/:id',  to: 'holo#category', as: :category
  get ':article_id', to: 'holo#article',  as: :article

  root to: 'holo#index'
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  include Cacheable
  before_filter :authenticate_user!
  layout 'admin'

  def index
    @articles = Article.visible
    @subscribers = Subscriber.all
  end

  def clear_cache
    destroy_aaaaaaall_cache!
    redirect_to :back, notice: "Os dados em cache do site foram apagados."
  end
end

app/views/admin/dashboard/index.html.erb
<section class="content-header">
  <h1>Dashboard <small>Painel</small></h1>
</section>

<section class="content">
  <div class="row">

    <div class="col-lg-4 col-md-4 col-xs-6">
      <div class="small-box bg-red">
        <div class="inner">
          <h3><%= @articles.size %></h3>
          <p>Artigos Publicados</p>
        </div>
        <div class="icon">
          <i class="ion ion-document"></i>
        </div>
        <%= link_to admin_articles_path, class: 'small-box-footer' do %>
          Ver Todos <i class="fa fa-arrow-circle-right"></i>
        <% end %>
      </div>
    </div>

    <div class="col-lg-4 col-md-4 col-xs-6">
      <div class="small-box bg-red">
        <div class="inner">
          <h3><%= @subscribers.size %></h3>
          <p>Assinantes de Newsletter</p>
        </div>
        <div class="icon">
          <i class="ion ion-at"></i>
        </div>
        <%= link_to admin_subscribers_path, class: 'small-box-footer' do %>
          Ver Todos <i class="fa fa-arrow-circle-right"></i>
        <% end %>
      </div>
    </div>

  </div>
</section>