config/routes.rb
Holoteca::Application.routes.draw do
  get '/não-encontramos',  to: "errors#error_404", as: :error_404

  scope '/admin' do
    devise_for :users,
      controllers: {
        registrations: 'admin/registrations',
        sessions: 'admin/sessions',
        passwords: 'admin/passwords'
      }
  end

  namespace :admin do
    root to: 'dashboard#index'
    get '/clean', to: "dashboard#clear_cache"
    resources :archives, only: [ :index, :create ]
    resources :categories, only: [ :index, :create, :edit, :update ]
    resources :subscribers
    resources :articles
  end

  get 'privacidade', to: 'statics#privacy', as: :privacy
  get 'anuncie', to: 'statics#contact', as: :contact
  post 'assine', to: 'statics#subscribe', as: :subscribe

  get '/uploads/archives/:id/:filename', to: 'archives#image'
  get '/tag/:id',    to: 'holo#tag',      as: :tag
  get '/autor/:id',  to: 'holo#author',   as: :author
  get '/holos/:id',  to: 'holo#category', as: :category
  get ':article_id', to: 'holo#article',  as: :article

  root to: 'holo#index'
end

app/views/shared/_featured.html.erb
<% unless resources.empty? %>
<li class="widget">
  <h2 class="widgettitle"><span>Você também vai querer saber...</span></h2>
  <ul class='featured'>
    <% resources.each do |article| %>
      <% cache([article, "featured"]) do %>
        <li class="post <%= article.category.to_param %>">
          <%= link_to article_path(article), title: article.title do %>
            <%= image_tag cover(article.cover_url), alt: article.title, size: '300x190' %>
          <% end %>
          <header>
            <span class="entry-category">
              <% if article.category %><%= link_to article.category.name, category_path(article.category) %><% end %>
            </span>
            <h4><%= link_to article.title, article_path(article), title: article.title %></h4>
          </header>
        </li>
      <% end %>
    <% end %>
  </ul>
</li>
<% end %>

app/views/shared/_fixed_bar.html.erb
<div id="fixed_bar" class="newsletter hidden-xs" style="display:none">
  <div class="container">
    <div class="row">
      <div class="col-md-12 middle">
        <%= form_tag(subscribe_path, method: :post, remote: true, class: 'is-subscription') do %>
          <h4 class="col-md-6">INSCREVA-SE PARA RECEBER AS NOVIDADES HOLOTECA</h4>
          <div class="col-md-6">
            <%= email_field_tag :email, nil, placeholder: 'seu@email.com.br', class: 'form-control subscribe', required: true %>
            <%= button_tag 'ASSINE', class: 'btn btn-danger' %>
          </div>
        <% end %>
      </div>
      <%= link_to image_tag('close.png', alt: 'Fechar', class: 'is-close', size: '24x24'), '#' %>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<% cache 'feet' do %>
<div id="footer-area">
  <div id="footer-widget">
    <div class="container">
      <div class="row">

        <div class="col-md-4 col-sm-6">
          <div class="widget widget_text">
            <div class="textwidget">
              <p><%= link_to image_tag('logos/brand-white.png', alt: 'Holoteca'), root_path, title: 'Holoteca' %></p>
              <p>
                <b>holo-</b> | <i>pref.</i> do grego: significa inteiro, todo.<br />
                <b>-teca</b> |é| <i>suf.</i> do latim: coleção ou local de armazenamento.
              </p>
            </div>
          </div>
        </div>

        <div class="col-md-4 col-sm-3 col-xs-6">
          <ul class='links'>
            <li><%= link_to 'Início', root_path, title: 'Página Inicial do Holoteca' %></li>
            <li><%= link_to 'Política de Privacidade', privacy_path, title: 'Política de Privacidade' %></li>
            <li><%= link_to 'Contato', contact_path, title: 'Anuncie ou Fale Conosco' %></li>
          </ul>
        </div>
          
        <% cache('bottom_menu', skip_digest: true) do %>
          <div class="col-xs-6 visible-xs">
            <ul class='links'>
              <% @categories.each do |category| %>
                <li class="menu-item">
                  <%= link_to category.name, category_path(category), title: category.name %>
                </li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="col-md-4 col-sm-3 col-xs-12 clearfix">
          <h4><b>Receba as novidades do Holoteca</b></h4>
          <%= form_tag(subscribe_path, method: :post, remote: true, class: 'is-subscription') do %>
            <div class="input-group">
              <%= email_field_tag :email, nil, placeholder: 'seu@email.com.br', class: 'form-contral subscribe', required: true %>
              <%= button_tag 'ASSINE', class: 'btn btn-danger' %>
            </div>
          <% end %>
        </div>

      </div>
    </div>
  </div>

  <footer id="bottom">
    <div class="container">
      <div class="row">
        <div class="col-sm-3 footer1">

          <div class="widget widget_g7_social">
            <ul class="horizontal circle">
              <li class="social-facebook">
                <a href="http://facebook.com/holoteca" title="Holoteca Fan Page">
                  <span class="social-box"><i class="fa fa-facebook"></i></span>
                </a>
              </li>

              <li class="social-google">
                <a href="https://plus.google.com/u/0/b/104599330917809356324/104599330917809356324/posts" title="Holoteca no Google Plus">
                  <span class="social-box"><i class="fa fa-google-plus"></i></span>
                </a>
              </li>

              <li class="social-instagram">
                <a href="http://instagram.com/holoteca" title="Holoteca no Instagram">
                  <span class="social-box"><i class="fa fa-instagram"></i></span>
                </a>
              </li>

              <li class="social-twitter">
                <a href="http://twitter.com/holoteca" title="Holoteca no Twitter">
                  <span class="social-box"><i class="fa fa-twitter"></i></span>
                </a>
              </li>
            </ul>
            <div class="clear"></div>
          </div>
        </div>

        <div class="col-sm-9 footer2">
          <a href="http://wipcodes.com" title='desenvolvimento wipcodes' class='pull-right wipcodes'>
            <%= image_tag('logos/wipcodes.png', alt: 'wipcodes') %></a>
          <span class='pull-right'>Copyright © 2015 Holoteca.</span>
        </div>
      </div>
    </div>
  </footer>
</div>
<% end %>

app/views/shared/_menu.html.erb
<ul id="mainmenu">
  <li class="menu-item">
    <%= link_to 'Início', root_path, class: 'parent', 'data-no-turbolink' => true %>
  </li>

  <% cache('top_menu', skip_digest: true) do %>
    <% @categories.each do |category| %>
      <li class="menu-item">
        <%= link_to category.name, category_path(category), title: category.name %>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/shared/_modal_social.html.erb
<div class="modal">
  <div data-remodal-id="curta" role="dialog">
    <button data-remodal-action="close" class="remodal-close"></button>
    <div class="col-sm-6">
      <h4><%= image_tag 'facebook-like.png', size: '24x24' %><br />
      <b>Além de artigos memoráveis, também colecionamos likes</b> </h4>
      <p>Curta nossa <u><a href="https://www.facebook.com/HolotecaHQ">página no Facebook</a></u> e receba nossos artigos na sua linha do tempo.</p>
    </div>
    <div class="col-sm-6">
      <div class="fb-like-box" data-href="https://www.facebook.com/HolotecaHQ" data-width="290" data-colorscheme="light" data-show-faces="true" data-header="false" data-stream="false" data-show-border="false"></div>
    </div>
    <br>
  </div>
</div>

app/views/shared/_segmentio.html.erb
<script type="text/javascript">
window.analytics=window.analytics||[],window.analytics.methods=["identify","group","track","page","pageview","alias","ready","on","once","off","trackLink","trackForm","trackClick","trackSubmit"],window.analytics.factory=function(t){return function(){var a=Array.prototype.slice.call(arguments);return a.unshift(t),window.analytics.push(a),window.analytics}};for(var i=0;i<window.analytics.methods.length;i++){var key=window.analytics.methods[i];window.analytics[key]=window.analytics.factory(key)}window.analytics.load=function(t){if(!document.getElementById("analytics-js")){var a=document.createElement("script");a.type="text/javascript",a.id="analytics-js",a.async=!0,a.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.io/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n)}},window.analytics.SNIPPET_VERSION="2.0.9",
window.analytics.load("f5f21poitt");
window.analytics.page();
</script>

app/views/shared/_shareholic.html.erb
<script type="text/javascript">
//<![CDATA[
  (function() {
    var shr = document.createElement('script');
    shr.setAttribute('data-cfasync', 'false');
    shr.src = '//dsms0mj1bbhn4.cloudfront.net/assets/pub/shareaholic.js';
    shr.type = 'text/javascript'; shr.async = true;
    shr.onload = shr.onreadystatechange = function() {
      var rs = this.readyState;
      if (rs && rs != 'complete' && rs != 'loaded') return;
      var site_id = 'f511a47408333eee5361c733bc39c04d';
      try { Shareaholic.init(site_id); } catch (e) {}
    };
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(shr, s);
  })();
//]]>
</script>

app/views/shared/_sidebar.html.erb
<div id="sidebar" class="rs col-md-4">
  <ul>

    <%= render partial: 'shared/featured', locals: { resources: @featured } if @featured %>
    <%= render partial: 'shared/featured', locals: { resources: @related } if @related %>

  <% cache('lastest_posts', skip_digest: true) do %>
    <li id="g7_posts-12" class="widget widget_g7_posts">
      <h2 class="widgettitle"><span>Últimas</span></h2>
      <ul class='lastest'>
        <% @lastest.each do |article| %>
          <% cache([article, "thumb"]) do %>
          <li class="<%= article.category.to_param %>">
            <div class="block-content">
              <div class="block-category">
                <% if article.category %><%= link_to article.category.name, category_path(article.category) %><% end %>
              </div>
              <h4 class="block-heading">
                <%= link_to article.title, article_path(article), title: article.title %>
              </h4>
              <div class="clear"></div>
            </div>
          </li>
          <% end %>
        <% end %>
      </ul>
    </li>
  <% end %>

    <li class='fb'>
      <div class="fb-like-box" data-href="https://www.facebook.com/HolotecaHQ" data-width="290" data-colorscheme="light" data-show-faces="true" data-header="false" data-stream="false" data-show-border="false"></div>
    </li>

    <li>
      <ins class="adsbygoogle"
           style="display:inline-block;width:300px;height:250px"
           data-ad-client="ca-pub-9856374304140488"
           data-ad-slot="8389583086"></ins>
      <script>(adsbygoogle = window.adsbygoogle || []).push({});</script>
    </li>

    <li>
      <a class="twitter-timeline" href="https://twitter.com/Holoteca" data-widget-id="454256714292809729">Tweets by @Holoteca</a>
      <script async src="//platform.twitter.com/widgets.js"></script>
    </li>

    <li>
      <ins class="adsbygoogle"
         style="display:inline-block;width:300px;height:250px"
         data-ad-client="ca-pub-9856374304140488"
         data-ad-slot="3313487089"></ins>
      <script>(adsbygoogle = window.adsbygoogle || []).push({});</script>
    </li>

    <li>
      <div class="g-page" data-href="//plus.google.com/u/0/104599330917809356324" data-rel="publisher"></div>
      <script type="text/javascript">
        window.___gcfg = {lang: 'pt-BR'};

        (function() {
          var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
          po.src = 'https://apis.google.com/js/platform.js';
          var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
        })();
      </script>
    </li>

    <li>
      <ins class="adsbygoogle"
        style="display:inline-block;width:300px;height:250px"
        data-ad-client="ca-pub-9856374304140488"
        data-ad-slot="7052355880"></ins>
      <script>(adsbygoogle = window.adsbygoogle || []).push({});</script>
    </li>

    <li>
      <ins class="adsbygoogle"
           style="display:inline-block;width:300px;height:250px"
           data-ad-client="ca-pub-9856374304140488"
           data-ad-slot="9866316286"></ins>
      <script>(adsbygoogle = window.adsbygoogle || []).push({}); </script>
    </li>

  </ul>
</div>